### ISSUE TITLE
LAMMPS link target in ~/bin/lmp

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/streaming-md-docker#1]
Is this script really linking correctly
https://github.com/Becksteinlab/streaming-md-docker/blob/1f2b1e537c59d370cfbbd5b0e1aeb3718314cdd4/docker/install_lammps.sh#L17

It looked to me as if the intention was to create `~/bin/lmp` but instead the script creates `/bin/lmp`.

**Comment by hmacdope** [comment]
Ah yes this is confusing. In fact we do want to link to `/bin/` as this is writable for all users, and `~/bin` is more flaky. I removed creating `~/bin` in latest.
