### ISSUE TITLE
Make public package 

### ISSUE THREAD

**Issue by hmacdope** [Becksteinlab/streaming-md-docker#8]
Packages are limited to private. I will need @orbeckst to give me public perms

**Comment by orbeckst** [comment]
I elevated you to admin — sorry, should have done that from the start. You _should_ be able to do most everything now.

**Comment by orbeckst** [comment]
I had to also change org settings to allow public packages (the default was only private).

I switched https://github.com/Becksteinlab/streaming-md-docker/pkgs/container/streaming-md-docker to public.

Please confirm @hmacdope .

**Comment by orbeckst** [comment]
I can see the package from a private browsing window without being logged into GH.
